services:
  # Database
  db:
    image: specchio-db:0.1.0
    container_name: specchio-db
    restart: always
    environment:
      # mysql base variables
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: specchio_db
      MYSQL_USER: specchio_user
      MYSQL_PASSWORD: specchio_password
    ports:
      - "3306:3306"
    volumes:
      # map local storage to sql container for data persistance
      - ./data:/var/lib/mysql:z
    networks:
      - specchio-network

    ###TRIAL: healthcheck - should ensure that DB is fully setup when webapp starts
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u$$MYSQL_USER", "-p$$MYSQL_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

  # Specchio Application
  webapp:
    image: specchio-webapp:0.1.2  # should move to :latest
    container_name: specchio-webapp
    depends_on: #wait for heathcheck of db to be completed
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "4848:4848" #admin console
    environment:
      # variables for glassfish to find db
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: specchio_db
      DB_USER: specchio_user
      DB_PASS: specchio_password
    networks:
      - specchio-network

networks:
  specchio-network:
    driver: bridge