version: '3.8'

services:
  # --- Database Container ---
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secure_root_password
      MYSQL_DATABASE: specchio
    volumes:
      # Init folder, read at first startup of db
      - ./db/init-db:/docker-entrypoint-initdb.d:ro
      ###- ./db/init-db:/docker-entrypoint-initdb.d:ro,z #:z for Fedora/Redhat
      
      # Persistent DB storage on the machine
      - ./db_storage:/var/lib/mysql
      ###- ./db_storage:/var/lib/mysql:z #:z for Fedora/Redhat
    networks:
      - specchio-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psecure_root_password"]
      interval: 5s
      timeout: 5s
      retries: 10

  # --- GlassFish Application Server ---
  webapp:
    image: specchio-webapp:0.2.1 #could be changed to :latest when tagged in dockerhub
    restart: always
    depends_on:
      database:
        condition: service_healthy

    ports:
      - "127.0.0.1:4848:4848" # expose admin console to local loopback only
    environment:
      - DB_USER=sdb_admin
      - DB_PASSWORD=sdb_admin_password
      - DB_NAME=specchio
    networks:
      - specchio-network

  # --- Reverse Proxy Shield ---
  reverse-proxy:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"   # http
      - "443:443" # https

    ###SELECT YOUR PROPER VERSION
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro #config file
      ###- ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro,z #:z for Fedora/Redhat
      - ./nginx/ssl:/etc/nginx/ssl:rw #SSL cert folder
      ###- ./nginx/ssl:/etc/nginx/ssl:rw,z #:z for Fedora/Redhat

    # Automatically generate a local self signed cert
    command: >
      sh -c "mkdir -p /etc/nginx/ssl; if [ ! -f /etc/nginx/ssl/server.crt ]; then apk add --no-cache openssl && openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/server.key -out /etc/nginx/ssl/server.crt -subj '/CN=localhost' -addext 'basicConstraints=critical,CA:TRUE'; fi; nginx -g 'daemon off;'"
    depends_on:
      - webapp
    networks:
      - specchio-network


# --- Isolated Brdge Network to connect the three containers ---
networks:
  specchio-network:
    driver: bridge