version: '3.8'

services:
  # --- 1. The Database Container ---
  database:
    # Using an official, production-ready PostgreSQL base image
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secure_root_password
      MYSQL_DATABASE: specchio
    volumes:
      # Automatically initializes the schema & applies upgrades sequentially on an empty database
      ###- ./db/init-db:/docker-entrypoint-initdb.d:ro
      - ./db/init-db:/docker-entrypoint-initdb.d:ro,z #:z for Fedora/Redhat
      # Persists structural user data safely on the host system drive
      ###- ./db_storage:/var/lib/mysql
      - ./db_storage:/var/lib/mysql:z #:z for Fedora/Redhat
    networks:
      - specchio-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psecure_root_password"]
      interval: 5s
      timeout: 5s
      retries: 10

  # --- 2. The GlassFish Application Server ---
  webapp:
    image: specchio-webapp:0.2.0 # Tells compose to use your exact built tag
    restart: always
    depends_on:
      database:
        condition: service_healthy
    # Ports remain completely hidden from the host network for isolation
    ports:
      - "127.0.0.1:4848:4848" # SECURE: Binds admin console ONLY to your local machine loopback
    environment:
      - DB_USER=sdb_admin
      - DB_PASSWORD=sdb_admin_password
      - DB_NAME=specchio
    networks:
      - specchio-network

  # --- 3. The Reverse Proxy Shield ---
  reverse-proxy:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"   # Local/Private Access (HTTP)
      - "443:443" # Public Cloud Access (HTTPS)
    volumes:
      ###- ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro,z #:z for Fedora/Redhat
      # Volume mount to securely drop in external public domain certificates if needed
      ###- ./nginx/ssl:/etc/nginx/ssl:rw
      - ./nginx/ssl:/etc/nginx/ssl:rw,z #:z for Fedora/Redhat
    # Automatically generates a local self-signed SSL certificate if one isn't present; is CA:TRUE! now 
    command: >
      sh -c "mkdir -p /etc/nginx/ssl; if [ ! -f /etc/nginx/ssl/server.crt ]; then apk add --no-cache openssl && openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/server.key -out /etc/nginx/ssl/server.crt -subj '/CN=localhost' -addext 'basicConstraints=critical,CA:TRUE'; fi; nginx -g 'daemon off;'"
    depends_on:
      - webapp
    networks:
      - specchio-network


# Isolated bridge network to prevent container exposure outside of Nginx
networks:
  specchio-network:
    driver: bridge